import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState} from "react";
import {data} from "../ekmek-fiyat";
import {Box, Slider, Stack, Typography} from "@mui/material";
import {BakeryDiningRounded, CurrencyLira} from "@mui/icons-material";

export default function Home() {

    const [search_ekmek_yil, set_search_ekmek_yil] = useState("");

    function valuetext(value) {
        return `${value}`;
    }

    const minDistance = 2;
    const [value1, setValue1] = useState([1950, 2022]);
    const handleChange1 = (event, newValue, activeThumb) => {
        if (!Array.isArray(newValue)) {
            return;
        }

        if (activeThumb === 0) {
            setValue1([Math.min(newValue[0], value1[1] - minDistance), value1[1]]);
        } else {
            setValue1([value1[0], Math.max(newValue[1], value1[0] + minDistance)]);
        }
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Ekmek.js!</a>
                </h1>


                {/*<input className={styles.input} type="text" name="yil"*/}
                {/*       placeholder={"Yıl Giriniz"}*/}
                {/*       value={search_ekmek_yil}*/}
                {/*       onChange={(event) => set_search_ekmek_yil(event.target.value)}*/}
                {/*/>*/}
                <Typography variant={"h4"}>Aşağıdaki barı kullanarak yıl aralıklarını belirleyebilirsiniz.</Typography>
                <Slider
                    sx={{color:"#0070f3", height:"10px"}}
                    getAriaLabel={() => 'Minimum distance'}
                    value={value1}
                    onChange={handleChange1}
                    valueLabelDisplay="auto"
                    marks
                    min={1950}
                    max={2022}
                    getAriaValueText={valuetext}
                />


                <div className={styles.all}>
                    {data.slice(value1[0] - 1950, 73 -  (2022 - value1[1])).map((item, index) => {
                        return (
                            <div className={styles.card} key={index}>

                                <Typography className={styles.description}>{item.yil}</Typography>
                                <Box sx={{mt:2}}>
                                    <Typography>{item.ekmekfiyati} <CurrencyLira sx={{color:"red", height:"20px", width:"20px"}}/> (1kg)</Typography>
                                    <Typography>1$ = {item.dolar} <CurrencyLira sx={{color:"red", height:"20px", width:"20px"}}/> </Typography>
                                    <Typography>Asgari ücret: {item.asgariucret} <CurrencyLira sx={{color:"red", height:"20px", width:"20px"}} /></Typography>
                                </Box>
                                <br/>
                                <Box sx={{display:"flex",flexDirection:"column", justifyContent:"center"}}>
                                    <Typography><b style={{color:"red"}}>*</b>Kaç adet ekmek alabiliyorum?</Typography>
                                    <Stack display={"flex"} flexDirection={"row"} gap={2}>
                                        <Typography>{Math.floor(parseFloat(item.asgariucret) / parseFloat(item.ekmekfiyati) * 5)} adet</Typography>
                                        <img height={"25px"} width={"25px"} style={{justifyContent:"center", alignItems:"center"}} src={"/bread.png"} alt={"ekmek"}/>
                                    </Stack>

                                </Box>

                            </div>
                        )
                    })

                    }
                </div>
            </main>

        </div>
    )
}

